# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.1.4

    steps:
      - checkout

      - run:
          name: Install awscli, doesn't come by default with the node:8.1.4 image
          # Python 2.7 comes by default with the Ubuntu container CircleCI uses.
          # However it doesn't comes with python-dev which is required for installing pip. If not
          # installed there will be an error when installing some package called "wheel". The
          # next two commands fetches the pip install script and installs pip. After installing
          # pip we add pip to the path (so we can subsequently use the command "pip"). This is
          # required because awscli has other dependencies which requires the existence of pip on
          # the path. Finally we install awscli.
          #
          # It should be noted this is a pretty ugly hack to get awscli in a Node container. In
          # CircleCI v1 the images came by default with awscli, so this mess wasn't required.
          command: |
              sudo apt-get install python-dev
              curl -O https://bootstrap.pypa.io/get-pip.py
              python get-pip.py --user
              export PATH=~/.local/bin:$PATH
              pip install awscli --upgrade --user

      - deploy:
          name: Deploy site to AWS S3 and invalidate the CloudFront cache
          command: |
              # CLOUDFRONT_ID is an environment variable defined in the CircleCI project, AWS CloudFront ID
              ~/.local/bin/aws s3 sync public/ s3://jonogmarteinn.is/ --delete
              ~/.local/bin/aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths '/*'
